override "libffi", version: "3.4.7"
override "libiconv", version: "1.18"
override "liblzma", version: "5.8.1"
override "libtool", version: "2.5.4"
override "libarchive", version: "3.8.1"
override "libyaml", version: "0.2.5"
override "makedepend", version: "1.0.9"
override "ncurses", version: "6.5"
override "nokogiri", version: "1.18.8"
override "libxml2", version: "2.14.3"
override "libxslt", version: "1.1.43"
override "openssl", version: "3.5.4"
override "pkg-config-lite", version: "0.28-1"
override :ruby, version: "3.4.8", openssl_gem: "3.3.0"
override "mixlib-log", version: "3.2.0"
override "ruby-windows-devkit-bash", version: "3.1.23-4-msys-1.0.18"
override "ruby-msys2-devkit", version: ENV.fetch("MSYS_OVERRIDE", "3.4.4-2")
override "util-macros", version: "1.19.0"
override "xproto", version: "7.0.31"
override "zlib", version: "1.3.1"
