#
# Author:: Marc Pardise (<marc@chef.io>)
# Copyright:: Copyright (c) Chef Software Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "chef/knife"

Chef::Knife.subcommand_loader.load_commands
commands = Chef::Knife::SubcommandLoader.generate_hash["_autogenerated_command_paths"]["plugins_paths"].keys

context "Command Sanity Check", :workstation do
  describe "knife" do
    include IntegrationSupport
    include KnifeSupport
    commands.each do |command|
      command_name = command.gsub("_", " ")
      modified_command, expected_result = case command_name
                                          when /knife/
                                            # because rspec is the actual executable running, the option parser error message
                                            # is invalid from within the test.
                                            next
                                          when /config (use|get|list) profile.*/
                                            # hyphenated special cases
                                            [command_name, /^USAGE: knife config #{$1}-profile.*/]
                                          when /(role|node|env) (env )?run list(.*)/
                                            # underscored special cases...
                                            env_part = $2.nil? ?  "" : "env_"
                                            ["#{$1} #{$2}run_list#{$3}", /^USAGE: knife #{$1} #{env_part}run_list#{$3}.*/]
                                          else
                                            [ command_name, /^USAGE: knife #{command_name}.*/]
                                          end

      full_command = "#{modified_command} --invalid-option"
      it full_command do
         knife(full_command, capture_init: true).should_fail(exit_code: 1, stdout: expected_result)
      end

    end
  end
end



